### ISSUE TITLE
Plus button is out of proportion

### ISSUE THREAD

**Issue by JamesClick** [srnd/clear#19]
![image](https://user-images.githubusercontent.com/15151345/33902878-4b11e1b4-df2b-11e7-96fd-f0b5df8e36a3.png)

-Regards,
`#staff-design`

**Comment by ItsDaGeek** [comment]
Hello,

I am contacting you in regards to issue #19 in the srnd/Clear code repository. It has come to my attention that this issue is come stale, and I am asking when it'll be fixed?

Thank you,

James Click
Intern in Media Production
srnd.org
(619) 800-5496 | jrc@srnd.org
