### ISSUE TITLE
Clear should be able to mass-communicate with parents/students via text message or phone call

### ISSUE THREAD

**Issue by brettneese** [srnd/Clear#2]
It would be nice if Clear could auto-text/call parents or students regarding any issues with the event, or reminding them of the schedule of the event, etc. We used a twilio script at HackGenY to call/text parents to remind them to pick their student up and it was incredibly effective.

**Comment by tjhorner** [comment]
Now on the todo list :+1:

**Comment by tjhorner** [comment]
This is possible with the robo-call function in case of emergency, and announcements can be sent to all attendees at once via SMS/Messenger/Companion.
