### ISSUE TITLE
Requiring students to sign-off on code of conduct

### ISSUE THREAD

**Issue by brettneese** [srnd/Clear#3]
One thing that was done at HackGenY was requiring students to sign off (via an iPad using a system called Smart Waiver) on the code of conduct before entering the event. 

I felt that this was super-effective, and though our ticket registration flow does include prompts about the code of conduct currently, I feel something should be done to make the COC more prevalent. 

(Perhaps simply putting together a mass email a few days before the event would be just as effective.)

**Comment by tjhorner** [comment]
> cross-platform checkin app

Since clear is mobile-friendly now, we can just add it there.

**Comment by tjhorner** [comment]
Students now need to sign a waiver, and agree to uphold the code of conduct upon registration.
