### ISSUE TITLE
Markdown code blocks don't render correctly

### ISSUE THREAD

**Issue by tjhorner** [srnd/Clear#8]
If I have this inside of an email:

![](http://puu.sh/g5CQL/acd8864b52.png)

And test it, it renders like this:

![](http://puu.sh/g5CZB/913446af6a.png)

Not really that major, but still a bug.

**Comment by tylermenezes** [comment]
I suspect this is a problem with markdown's lack of a formal spec -- you probably need the two-spaces-at-the-end-of-the-line thing to make it multiline.

**Comment by tjhorner** [comment]
I think this is fixed
